---
title: "Stormw Water Analysis V4 - Kracken"
author: "Kaelyn Nannini"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load libraries}

#Load libraries

library("dplyr")
library("ggplot2")
library("vegan")
library("RColorBrewer")
library("zCompositions")
library("lattice")
library("ggpubr")
library("tidyr") #needs to tidy data
```

```{r Load data}

#read in data and store in df, filter to only include only bacteria
storm <- read.table("clean_sw_kracken.txt", header = T, stringsAsFactors = T)
swmeta <- read.csv("sample_info.csv", stringsAsFactors = T)
#filter data to only include Bacterial phyla counts
gcnts <- storm %>%
  filter(kingdom == "Bacteria") %>%
  dplyr::select(2:13, 19) %>%
  group_by(genus) %>%
  summarise_all(sum)

#Create second dataframe with phylums as rownames
genera <- gcnts$genus
g_counts <- gcnts[, 2:13]
rownames(g_counts) <- genera

#extra rain metadata
rmeta <- swmeta %>%
  dplyr::select(Sample, Rain)
```


```{r Calculate genera richness}
#richness
richness = data.frame(matrix(nrow = 12, ncol = 2))

#make a dataframe with the first row in the column has the site name and the second column has the number of species
for (i in 1:12) { 
  richness[i, 2] <- length(which(g_counts[i]>0)) #counts number of times there's a counts greater than 0
  richness[i, 1] <- colnames(g_counts[i]) 
}
colnames(richness) <- c("Sample", "Richness")
meta_rich <- inner_join(richness, rmeta)


ggplot(meta_rich, mapping = aes(x= Sample, y = Richness, fill = Rain)) + 
  geom_bar(stat = "identity") + 
  theme_classic()


#get total counts for all samples
totals <-colSums(g_counts)
```

```{r Calculate shannon diversity}
#shannon diversity
shannon <- diversity(t(g_counts))
shannondf <- data.frame('Sample' = as.factor(names(shannon)), "ShannonDiversity" = shannon) #create dataframe from named number
shannon_meta <- inner_join(shannondf, rmeta)
ggplot(shannon_meta, mapping = aes(x= Sample, y = ShannonDiversity, fill = Rain)) + geom_bar(stat = "identity") + theme_classic()
```

``` {r calculate evenness}

#Pielou's evenness
evenness = shannon/log(richness[2])
df <- data.frame(names(shannon), evenness[1])
colnames(df) <- c("Sample", "Evenness")
even_meta <-inner_join(df, rmeta)
ggplot(even_meta, mapping = aes(x= Sample, y = Evenness, fill = Rain)) + 
  geom_bar(stat = "identity") +
  theme_classic()

```

```{r Relative Abundances}
#calculate relative abundances and plot them
rcnt <- nrow(gcnts)
ccnt <- ncol(gcnts)

r_abund <- data.frame(matrix(nrow=rcnt, ncol = ccnt)) #create dataframe with same number and rows and columns as pcnts
colnames(r_abund) <- colnames(gcnts) #rename the columns as the same as gcnts
r_abund[1] <- gcnts[1]

for(i in 2:13) {
  r_abund[i] <- round(gcnts[i]/totals[i-1], 4) #divide count of phylum of given site by the total number of features for that site
}

#filter for relative abundances greater than 1% and 5%
above1 <- r_abund %>% filter_at(2:13, (any_vars(. > .01))) 
above2<- r_abund %>% filter_at(2:13, (any_vars(. > .025)))

#create tidy plots of relative abundances for graphing purposes
tidy_above1 <- above1 %>%
  pivot_longer(EB29:EB40, names_to = "Sites", values_to = "Abundances")
tidy_above2 <- above2 %>%   
  pivot_longer(EB29:EB40, names_to = "Sites", values_to = "Abundances")
```

```{r Relative abundance plots}
ggplot(tidy_above1, aes(x=Sites, y=Abundances, fill=genus)) +
  geom_bar(stat="identity") + theme_classic()

ggplot(tidy_above2, aes(x=Sites, y=Abundances, fill=genus)) +
  geom_bar(stat="identity") + 
  theme_classic()

```


```{r CLR transform and NMDS}

#CLR transform
bac_z <- cmultRepl(as.matrix(g_counts), output = 'p-counts') #create z scores
clr <- function(x) sweep(log(x), 1, rowMeans(log(x)), "-")
bac_tx <- data.frame(t(clr(t(bac_z)))) #clr transform data

#NMDS
#bact_m <- as.matrix(t(bac_tx))
Bact_nmds = metaMDS(t(bac_tx), distance = "euclidean")
bact_scores = as.data.frame(scores(Bact_nmds))
```
```{r Plot NMDS}
#Filter Metadata
meta2 <- swmeta %>%
  dplyr::select(Sample, Rain)
bact_scores$Sample <- as.factor(rownames(bact_scores))
meta2$Sample <- as.factor(meta2$Sample)
bact_scores2 <- inner_join(bact_scores, meta2)

#make plot
B_T <- ggplot(data = bact_scores2, aes(x = NMDS1, y = NMDS2, color = Rain)) +
  geom_point() + 
  theme_classic()
B_T 
```

```{r Ordiplot of NMDS}
ordiplot(Bact_nmds, display = "sites")
```
